* Installation

** Dependencies
  This project uses Maven to fetch its dependencies.
  Maven is usually provided by Linux systems.  Use your package
  manager to install it.  For example, on Debina-like systems
  you would run:

  #+begin_src sh
    sudo apt-get install mvn
  #+end_src

  On RHEL-like systems you would run:

  #+begin_src sh
    sudo dnf install mvn
  #+end_src

  Installation instructions for MS Windows and Apple OS can be found
  here:
  - MS Windows :: http://www.mkyong.com/maven/how-to-install-maven-in-windows/
  - Apple OS X :: http://stackoverflow.com/questions/8826881/maven-install-on-mac-os-x

** Sources
   Run:
   #+begin_src sh
     git clone https://github.com/wvxvw/intro-to-java.git
   #+end_src

   Or download the project sources from
   https://github.com/wvxvw/intro-to-java/archive/master.zip

* Building
  Run:
  #+begin_src sh
    mvn package
  #+end_src
  to generate an executable JAR file.  The file will be generated in
  [[./target/assignments-1.0-SNAPSHOT.jar]].  Be patient while Maven resolves
  its dependencies.  Repeated builds will take significantly less time.

* Using
  Run:
  #+begin_src sh
    java -jar ./target/assignments-1.0-SNAPSHOT.jar --help
  #+end_src
  to read the available options.

  Run: 
  #+begin_src sh
    java -jar ./target/assignments-1.0-SNAPSHOT.jar -a N
  #+end_src
  where =N= is the assignment number, to load N'th assignment.

* Logging
  The project uses =logback= adapter to =log4j=.  The configuration file is
  here: [[./etc/log4j.properties]].  In order to affect the amount of information
  printed adjust the value of =log4j.rootLogger= property (possible values are
  =DEBUG=, =INFO=, =WARN= and =ERROR=.

* Bonus Reading Material
  You can integrate Maven POM files into many popular code editors such
  as Intellij IDEA, Eclipse or Netbeans.
  - Netbeans :: https://platform.netbeans.org/tutorials/nbm-maven-quickstart.html
  - Eclipse :: http://books.sonatype.com/m2eclipse-book/reference/creating-sect-importing-projects.html
  - Intellij IDEA :: https://www.jetbrains.com/idea/help/maven-2.html
